// WhiskyMBTI Data — shared via window.WHISKY_APP_DATA

window.WHISKY_APP_DATA = {

QUIZ_QUESTIONS: [
  // E/I
  {
    id: 'q1', dim: 'EI',
    ko: '파티나 모임에서 나는…', en: 'At a party or gathering, I tend to…',
    A: { ko: '새로운 사람들과 어울리며 에너지를 얻는다', en: 'Energize by meeting new people', val: 'E' },
    B: { ko: '소수와 깊은 대화를 즐기거나 일찍 떠난다', en: 'Prefer deep talks with a few, or leave early', val: 'I' }
  },
  {
    id: 'q2', dim: 'EI',
    ko: '긴 하루를 보낸 후 나는…', en: 'After a long day, I recharge by…',
    A: { ko: '친구들과 어울리며 기분을 푼다', en: 'Hanging out with friends', val: 'E' },
    B: { ko: '혼자만의 조용한 시간을 갖는다', en: 'Having quiet time alone', val: 'I' }
  },
  {
    id: 'q3', dim: 'EI',
    ko: '위스키를 마실 때 이상적인 장면은…', en: 'My ideal whisky moment is…',
    A: { ko: '바에서 여러 사람과 함께', en: 'At a lively bar with company', val: 'E' },
    B: { ko: '집에서 혼자 음악과 함께', en: 'Home alone with music', val: 'I' }
  },
  // N/S
  {
    id: 'q4', dim: 'NS',
    ko: '새로운 위스키를 고를 때 나는…', en: 'When choosing a new whisky, I…',
    A: { ko: '독특하고 실험적인 것에 끌린다', en: 'Go for something unique and experimental', val: 'N' },
    B: { ko: '믿을 수 있는 검증된 제품을 고른다', en: 'Stick to trusted, well-reviewed classics', val: 'S' }
  },
  {
    id: 'q5', dim: 'NS',
    ko: '대화할 때 나는 주로…', en: 'In conversation, I tend to focus on…',
    A: { ko: '아이디어, 가능성, 미래에 대해 이야기한다', en: 'Ideas, possibilities, and future concepts', val: 'N' },
    B: { ko: '실제 경험, 사실, 구체적인 것을 이야기한다', en: 'Real experiences, facts, concrete details', val: 'S' }
  },
  {
    id: 'q6', dim: 'NS',
    ko: '위스키의 복잡한 풍미를 마주할 때…', en: 'When tasting complex whisky flavours…',
    A: { ko: '상상력을 발휘해 다양한 향을 찾아낸다', en: 'I love finding hidden layers and meanings', val: 'N' },
    B: { ko: '명확하게 느껴지는 맛 위주로 즐긴다', en: 'I focus on clear, tangible flavours', val: 'S' }
  },
  // T/F
  {
    id: 'q7', dim: 'TF',
    ko: '친구가 고민을 털어놓을 때 나는…', en: 'When a friend shares a problem, I…',
    A: { ko: '해결책과 논리적인 조언을 먼저 찾는다', en: 'Offer solutions and logical advice', val: 'T' },
    B: { ko: '공감하고 감정적으로 지지해준다', en: 'Empathize and offer emotional support', val: 'F' }
  },
  {
    id: 'q8', dim: 'TF',
    ko: '위스키를 평가할 때 더 중요한 것은…', en: 'When evaluating a whisky, more important is…',
    A: { ko: '숙성 연도, 증류소, 가성비 등 객관적 스펙', en: 'Objective specs: age, distillery, value', val: 'T' },
    B: { ko: '그 순간의 감성, 분위기, 감동', en: 'The mood, emotion, and feeling of the moment', val: 'F' }
  },
  {
    id: 'q9', dim: 'TF',
    ko: '중요한 결정을 내릴 때…', en: 'When making important decisions, I rely on…',
    A: { ko: '분석하고 논리적으로 최선을 판단한다', en: 'Logic, analysis, and objective reasoning', val: 'T' },
    B: { ko: '직관과 나의 가치관을 따른다', en: 'Intuition and personal values', val: 'F' }
  },
  // J/P
  {
    id: 'q10', dim: 'JP',
    ko: '여행을 계획할 때 나는…', en: 'When planning a trip, I…',
    A: { ko: '세세한 일정을 미리 짜두는 편이다', en: 'Plan detailed itineraries in advance', val: 'J' },
    B: { ko: '대략적인 방향만 정하고 즉흥적으로 간다', en: 'Keep it loose and decide on the fly', val: 'P' }
  },
  {
    id: 'q11', dim: 'JP',
    ko: '마감이나 약속이 있을 때 나는…', en: 'With deadlines or commitments, I…',
    A: { ko: '미리 준비해 여유 있게 마친다', en: 'Finish ahead of time, stay ahead', val: 'J' },
    B: { ko: '마감 직전에 집중력이 폭발한다', en: 'Hit peak focus right before the deadline', val: 'P' }
  },
  {
    id: 'q12', dim: 'JP',
    ko: '오늘 저녁 마실 위스키는…', en: "Tonight's whisky choice…",
    A: { ko: '이미 마음속에 정해진 것이 있다', en: "I've already decided what I want", val: 'J' },
    B: { ko: '그날의 기분에 따라 즉흥적으로 고른다', en: 'Depends on the mood of the moment', val: 'P' }
  },
],

WHISKY_DATA: {
  INTJ: {
    name: "Lagavulin 16",
    nameKo: "라가불린 16년",
    region: "Islay, Scotland",
    regionKo: "스코틀랜드 아일라",
    age: "16 Years",
    abv: "43%",
    color: "#8B3A1A",
    tags: ["Peaty", "Smoky", "Complex"],
    tagsKo: ["피트", "스모키", "복잡함"],
    desc: "Deep, brooding, and unmistakably powerful — like the Architect, Lagavulin 16 reveals its complexity only to those patient enough to listen.",
    descKo: "깊고 어두우며 강렬한 — 전략가처럼, 라가불린 16년은 충분한 시간을 가진 자에게만 그 복잡함을 드러냅니다.",
    tasting: "Intense peat smoke, sea salt, dark chocolate, iodine, long smoky finish",
    tastingKo: "강렬한 피트 스모크, 바다 소금, 다크 초콜릿, 아이오딘, 긴 스모키 여운",
    pair: "Dark chocolate, blue cheese",
    pairKo: "다크 초콜릿, 블루치즈",
    emoji: "🏰", character: "Architect", characterKo: "건축가",
    flavor: { peaty: 95, sweet: 20, spicy: 55, fruity: 15, oaky: 70 },
  },
  INTP: {
    name: "Glenfarclas 21",
    nameKo: "글렌파클라스 21년",
    region: "Speyside, Scotland",
    regionKo: "스코틀랜드 스페이사이드",
    age: "21 Years", abv: "43%", color: "#6B3E1A",
    tags: ["Sherry", "Complex", "Dry"],
    tagsKo: ["셰리", "복잡함", "드라이"],
    desc: "The Logician's dram — multi-layered, endlessly analytical, never quite finished revealing itself.",
    descKo: "논리학자의 위스키 — 다층적이고 끊임없이 분석적이며, 결코 완전히 드러나지 않습니다.",
    tasting: "Sherry oak, orange peel, walnut, raisins, dry finish",
    tastingKo: "셰리 오크, 오렌지 껍질, 호두, 건포도, 드라이 피니시",
    pair: "Almonds, aged cheese",
    pairKo: "아몬드, 숙성 치즈",
    emoji: "🔭", character: "Logician", characterKo: "논리학자",
    flavor: { peaty: 10, sweet: 40, spicy: 30, fruity: 50, oaky: 85 },
  },
  ENTJ: {
    name: "Dalmore 18",
    nameKo: "달모어 18년",
    region: "Highland, Scotland",
    regionKo: "스코틀랜드 하이랜드",
    age: "18 Years", abv: "43%", color: "#7A2E0E",
    tags: ["Sherry", "Rich", "Powerful"],
    tagsKo: ["셰리", "리치", "파워풀"],
    desc: "The Commander demands presence. Dalmore 18's commanding richness and stag emblem match a natural-born leader.",
    descKo: "통솔자는 존재감을 요구합니다. 달모어 18년의 압도적인 풍미와 수사슴 엠블럼은 타고난 리더를 닮았습니다.",
    tasting: "Orange marmalade, ginger, dark chocolate, spice, velvet finish",
    tastingKo: "오렌지 마멀레이드, 진저, 다크 초콜릿, 스파이스, 벨벳 피니시",
    pair: "Cigar, espresso",
    pairKo: "시가, 에스프레소",
    emoji: "👑", character: "Commander", characterKo: "통솔자",
    flavor: { peaty: 15, sweet: 70, spicy: 80, fruity: 60, oaky: 75 },
  },
  ENTP: {
    name: "Springbank 15",
    nameKo: "스프링뱅크 15년",
    region: "Campbeltown, Scotland",
    regionKo: "스코틀랜드 캠벨타운",
    age: "15 Years", abv: "46%", color: "#5C3317",
    tags: ["Unique", "Briny", "Dynamic"],
    tagsKo: ["유니크", "브라이니", "다채로움"],
    desc: "Unpredictable, rule-breaking, and brilliantly unique — Springbank mirrors the Debater's restless genius.",
    descKo: "예측 불가능하고 규칙을 깨며 독특하게 빛나는 — 스프링뱅크는 변론가의 지칠 줄 모르는 천재성을 반영합니다.",
    tasting: "Sea salt, vanilla, light peat, tropical fruit, coastal brine",
    tastingKo: "바다소금, 바닐라, 가벼운 피트, 열대 과일, 해안의 짠내",
    pair: "Oysters, smoked salmon",
    pairKo: "굴, 훈제 연어",
    emoji: "⚡", character: "Debater", characterKo: "변론가",
    flavor: { peaty: 40, sweet: 45, spicy: 50, fruity: 65, oaky: 40 },
  },
  INFJ: {
    name: "Glenfiddich 21 Gran Reserva",
    nameKo: "글렌피딕 21년 그란 레세르바",
    region: "Speyside, Scotland",
    regionKo: "스코틀랜드 스페이사이드",
    age: "21 Years", abv: "40%", color: "#9B5E1A",
    tags: ["Rum Finish", "Complex", "Silky"],
    tagsKo: ["럼 피니시", "복잡함", "실키"],
    desc: "Rare, deeply layered, and quietly profound — the Advocate's whisky holds truths only the perceptive can find.",
    descKo: "희귀하고 깊이 층을 이루며 조용히 심오한 — 옹호자의 위스키는 예리한 자만이 찾을 수 있는 진실을 담고 있습니다.",
    tasting: "Caribbean rum, tropical fruit, ginger, vanilla, silky long finish",
    tastingKo: "카리브해 럼, 열대 과일, 생강, 바닐라, 실키한 긴 피니시",
    pair: "Dark fruit cake, mango",
    pairKo: "다크 과일 케이크, 망고",
    emoji: "🌙", character: "Advocate", characterKo: "옹호자",
    flavor: { peaty: 5, sweet: 85, spicy: 35, fruity: 90, oaky: 55 },
  },
  INFP: {
    name: "Auchentoshan Three Wood",
    nameKo: "어켄토산 쓰리 우드",
    region: "Lowland, Scotland",
    regionKo: "스코틀랜드 로우랜드",
    age: "NAS", abv: "43%", color: "#8B6E3A",
    tags: ["Triple Distilled", "Gentle", "Sweet"],
    tagsKo: ["삼중증류", "부드러움", "달콤함"],
    desc: "Three casks, countless stories — Auchentoshan holds a universe of gentle complexity, just like the Mediator.",
    descKo: "세 오크, 수많은 이야기 — 어켄토산은 중재자처럼 부드러운 복잡함의 세계를 담고 있습니다.",
    tasting: "Sherry, bourbon, port wine, sweet dried fruit, toffee",
    tastingKo: "셰리, 버번, 포트, 달콤한 말린 과일, 토피",
    pair: "Milk chocolate, berries",
    pairKo: "밀크 초콜릿, 베리류",
    emoji: "🌸", character: "Mediator", characterKo: "중재자",
    flavor: { peaty: 5, sweet: 90, spicy: 20, fruity: 80, oaky: 50 },
  },
  ENFJ: {
    name: "Glenmorangie Signet",
    nameKo: "글렌모렌지 시그넷",
    region: "Highland, Scotland",
    regionKo: "스코틀랜드 하이랜드",
    age: "NAS", abv: "46%", color: "#B5721F",
    tags: ["Choc Malt", "Rich", "Elegant"],
    tagsKo: ["초콜릿 몰트", "리치", "우아함"],
    desc: "Crafted with rare chocolate malt and immense care — the Protagonist makes every experience feel extraordinary.",
    descKo: "희귀한 초콜릿 몰트로 정성스럽게 제조된 — 선도자는 모든 경험을 특별하게 만드는 힘을 가졌습니다.",
    tasting: "Espresso, dark chocolate, orange zest, spice, creamy finish",
    tastingKo: "에스프레소, 다크 초콜릿, 오렌지 제스트, 스파이스, 크리미 피니시",
    pair: "Truffle chocolate, espresso",
    pairKo: "트러플 초콜릿, 에스프레소",
    emoji: "✨", character: "Protagonist", characterKo: "선도자",
    flavor: { peaty: 10, sweet: 75, spicy: 65, fruity: 60, oaky: 70 },
  },
  ENFP: {
    name: "Balvenie Caribbean Cask 14",
    nameKo: "발베니 카리브해 캐스크 14년",
    region: "Speyside, Scotland",
    regionKo: "스코틀랜드 스페이사이드",
    age: "14 Years", abv: "43%", color: "#C4882A",
    tags: ["Rum Cask", "Tropical", "Vibrant"],
    tagsKo: ["럼 캐스크", "트로피칼", "생동감"],
    desc: "Sun-drenched, joyful, and full of surprises — the Campaigner's spirit in a glass of liquid sunshine.",
    descKo: "햇살로 가득하고 기쁨이 넘치며 놀라움으로 가득한 — 활동가의 정신이 액체 햇살 한 잔에 담겼습니다.",
    tasting: "Tropical fruit, vanilla, cream, caramel, light spice",
    tastingKo: "열대 과일, 바닐라, 크림, 캐러멜, 가벼운 스파이스",
    pair: "Pineapple, coconut dessert",
    pairKo: "파인애플, 코코넛 디저트",
    emoji: "🌺", character: "Campaigner", characterKo: "활동가",
    flavor: { peaty: 5, sweet: 92, spicy: 25, fruity: 95, oaky: 35 },
  },
  ISTJ: {
    name: "Glenfarclas 12",
    nameKo: "글렌파클라스 12년",
    region: "Speyside, Scotland",
    regionKo: "스코틀랜드 스페이사이드",
    age: "12 Years", abv: "43%", color: "#6E4420",
    tags: ["Sherry", "Reliable", "Classic"],
    tagsKo: ["셰리", "안정감", "클래식"],
    desc: "Steadfast, traditional, and utterly dependable — the Logistician's whisky never lets you down.",
    descKo: "확고하고 전통적이며 완전히 믿을 수 있는 — 현실주의자의 위스키는 절대 실망시키지 않습니다.",
    tasting: "Sherry, oak, raisins, cinnamon, warm spice",
    tastingKo: "셰리, 오크, 건포도, 시나몬, 따뜻한 스파이스",
    pair: "Cheese platter, walnuts",
    pairKo: "치즈 플래터, 호두",
    emoji: "📚", character: "Logistician", characterKo: "현실주의자",
    flavor: { peaty: 15, sweet: 60, spicy: 55, fruity: 45, oaky: 85 },
  },
  ISFJ: {
    name: "Glengoyne 15",
    nameKo: "글렌고인 15년",
    region: "Highland, Scotland",
    regionKo: "스코틀랜드 하이랜드",
    age: "15 Years", abv: "43%", color: "#9E6B2E",
    tags: ["Unpeated", "Gentle", "Honeyed"],
    tagsKo: ["언피티드", "부드러움", "꿀향"],
    desc: "No smoke, just warmth — Glengoyne's rare air-dried malt embodies the Defender's quiet, caring strength.",
    descKo: "연기 없이 따뜻함만 — 글렌고인의 공기 건조 몰트는 수호자의 조용하고 배려 깊은 강인함을 담고 있습니다.",
    tasting: "Honey, green apple, ginger, gentle oak, creamy",
    tastingKo: "꿀, 청사과, 생강, 부드러운 오크, 크리미",
    pair: "Apple tart, honey",
    pairKo: "애플 타르트, 꿀",
    emoji: "🍀", character: "Defender", characterKo: "수호자",
    flavor: { peaty: 0, sweet: 85, spicy: 30, fruity: 75, oaky: 60 },
  },
  ESTJ: {
    name: "Highland Park 18",
    nameKo: "하이랜드 파크 18년",
    region: "Orkney, Scotland",
    regionKo: "스코틀랜드 오크니",
    age: "18 Years", abv: "43%", color: "#7A3E1A",
    tags: ["Balanced", "Sherry", "Peaty"],
    tagsKo: ["균형", "셰리", "피트"],
    desc: "The Executive's perfect balance — sherry sweetness and Orcadian peat in masterful equilibrium.",
    descKo: "경영자의 완벽한 균형 — 셰리의 달콤함과 오크니의 피트가 완벽하게 균형을 이룹니다.",
    tasting: "Heather honey, light peat, sherry, orange, warm spice",
    tastingKo: "헤더 꿀, 가벼운 피트, 셰리, 오렌지, 따뜻한 스파이스",
    pair: "Smoked salmon, cheddar",
    pairKo: "훈제 연어, 체더 치즈",
    emoji: "🎯", character: "Executive", characterKo: "경영자",
    flavor: { peaty: 45, sweet: 65, spicy: 60, fruity: 50, oaky: 75 },
  },
  ESFJ: {
    name: "Bunnahabhain 12",
    nameKo: "부나하벤 12년",
    region: "Islay, Scotland",
    regionKo: "스코틀랜드 아일라",
    age: "12 Years", abv: "46.3%", color: "#A87030",
    tags: ["Unpeated", "Nutty", "Approachable"],
    tagsKo: ["언피티드", "넛티", "친근함"],
    desc: "Islay without the smoke — Bunnahabhain's warmth and approachability mirror the Consul's welcoming nature.",
    descKo: "연기 없는 아일라 — 부나하벤의 따뜻함과 친근함은 집정관의 환영하는 본성을 반영합니다.",
    tasting: "Nuts, sea salt, dark chocolate, dried fruit, gentle finish",
    tastingKo: "견과류, 바다 소금, 다크 초콜릿, 말린 과일, 부드러운 피니시",
    pair: "Nut cake, Camembert",
    pairKo: "견과류 케이크, 카망베르",
    emoji: "🤝", character: "Consul", characterKo: "집정관",
    flavor: { peaty: 10, sweet: 60, spicy: 35, fruity: 55, oaky: 65 },
  },
  ISTP: {
    name: "Ardbeg 10",
    nameKo: "아드벡 10년",
    region: "Islay, Scotland",
    regionKo: "스코틀랜드 아일라",
    age: "10 Years", abv: "46%", color: "#5A2E10",
    tags: ["Peaty", "Citrus", "Dynamic"],
    tagsKo: ["피트", "시트러스", "다이나믹"],
    desc: "Intense peat cut by unexpected citrus brightness — the Virtuoso's skill reveals beauty in extremes.",
    descKo: "강렬한 피트를 예상치 못한 시트러스 밝음이 잘라내는 — 장인의 기술은 극한에서 아름다움을 드러냅니다.",
    tasting: "Intense peat, lemon, lime, tar, vanilla, long smoky finish",
    tastingKo: "강렬한 피트, 레몬, 라임, 타르, 바닐라, 긴 스모키 피니시",
    pair: "Smoked meats, olives",
    pairKo: "훈제 고기, 올리브",
    emoji: "🔧", character: "Virtuoso", characterKo: "장인",
    flavor: { peaty: 98, sweet: 25, spicy: 50, fruity: 30, oaky: 55 },
  },
  ISFP: {
    name: "Aberlour 16",
    nameKo: "아벌라워 16년",
    region: "Speyside, Scotland",
    regionKo: "스코틀랜드 스페이사이드",
    age: "16 Years", abv: "43%", color: "#B87840",
    tags: ["Double Cask", "Fruity", "Gentle"],
    tagsKo: ["더블캐스크", "과일향", "부드러움"],
    desc: "Two casks, endless nuance — Aberlour's gentle complexity suits the Adventurer's free and sensitive soul.",
    descKo: "두 오크, 끝없는 뉘앙스 — 아벌라워의 부드러운 복잡함은 모험가의 자유롭고 섬세한 영혼과 잘 어울립니다.",
    tasting: "Red berries, spice, sherry sweetness, gentle oak, smooth",
    tastingKo: "붉은 과일, 스파이스, 셰리 달콤함, 부드러운 오크, 스무스",
    pair: "Strawberry cake, Brie",
    pairKo: "딸기 케이크, 브리 치즈",
    emoji: "🎨", character: "Adventurer", characterKo: "모험가",
    flavor: { peaty: 5, sweet: 80, spicy: 45, fruity: 85, oaky: 55 },
  },
  ESTP: {
    name: "Talisker 10",
    nameKo: "탈리스커 10년",
    region: "Isle of Skye, Scotland",
    regionKo: "스코틀랜드 스카이 섬",
    age: "10 Years", abv: "45.8%", color: "#7B3B18",
    tags: ["Maritime", "Peaty", "Spicy"],
    tagsKo: ["해양", "피트", "스파이시"],
    desc: "Born from Skye's wild seas — Talisker's bold, briny thrill matches the Entrepreneur's fearless energy.",
    descKo: "스카이 섬의 거친 바다에서 태어난 — 탈리스커의 대담하고 짠 스릴은 사업가의 두려움 없는 에너지와 일치합니다.",
    tasting: "Sea salt, pepper, peat, sweet spice, long warming finish",
    tastingKo: "바다 소금, 후추, 피트, 달콤한 스파이스, 길고 따뜻한 피니시",
    pair: "Oysters, smoked meat",
    pairKo: "굴, 훈제 고기",
    emoji: "🌊", character: "Entrepreneur", characterKo: "사업가",
    flavor: { peaty: 70, sweet: 30, spicy: 90, fruity: 25, oaky: 45 },
  },
  ESFP: {
    name: "Monkey Shoulder",
    nameKo: "몽키숄더",
    region: "Speyside, Scotland",
    regionKo: "스코틀랜드 스페이사이드",
    age: "NAS", abv: "40%", color: "#D4962A",
    tags: ["Blended Malt", "Smooth", "Fun"],
    tagsKo: ["블렌디드 몰트", "스무스", "펀"],
    desc: "Three malts blended for pure joy — Monkey Shoulder is the life of the party, just like the Entertainer.",
    descKo: "순수한 즐거움을 위해 세 가지 몰트를 블렌딩한 — 몽키숄더는 파티의 분위기를 주도하는 연예인처럼 활기차게 빛납니다.",
    tasting: "Vanilla, honey, spiced orange, smooth creamy finish",
    tastingKo: "바닐라, 꿀, 스파이시 오렌지, 부드럽고 크리미한 피니시",
    pair: "Cocktail mixer, burgers",
    pairKo: "칵테일 믹서, 버거",
    emoji: "🎭", character: "Entertainer", characterKo: "연예인",
    flavor: { peaty: 5, sweet: 88, spicy: 30, fruity: 70, oaky: 35 },
  },
},

// Price range & where to buy
WHISKY_PRICE: {
  INTJ: { krw: "90,000–120,000", usd: "$70–90",   tier: "premium",  tierKo: "프리미엄",
    buy: ["이마트 와인앤모어", "CU 주류특화점", "롯데마트 주류코너"],
    online: ["https://cu.bgfretail.com", "https://whiskybase.com"] },
  INTP: { krw: "70,000–95,000",  usd: "$55–75",   tier: "mid",      tierKo: "미드레인지",
    buy: ["홈플러스 주류코너", "이마트 와인앤모어", "GS25 주류특화점"],
    online: ["https://whiskybase.com"] },
  ENTJ: { krw: "130,000–180,000",usd: "$100–140", tier: "luxury",   tierKo: "럭셔리",
    buy: ["신세계 강남 주류관", "갤러리아 명품관", "현대백화점 주류"],
    online: ["https://thewhiskyexchange.com"] },
  ENTP: { krw: "95,000–130,000", usd: "$75–100",  tier: "premium",  tierKo: "프리미엄",
    buy: ["이마트 와인앤모어", "보틀벙커", "스카치앤바"],
    online: ["https://thewhiskyexchange.com"] },
  INFJ: { krw: "180,000–240,000",usd: "$140–185", tier: "luxury",   tierKo: "럭셔리",
    buy:["신세계 강남 주류관", "현대백화점 주류", "롯데 에비뉴엘"],
    online: ["https://masterofmalt.com"] },
  INFP: { krw: "65,000–85,000",  usd: "$50–65",   tier: "mid",      tierKo: "미드레인지",
    buy: ["홈플러스 주류코너", "이마트 와인앤모어", "CU 주류특화점"],
    online: ["https://whiskybase.com"] },
  ENFJ: { krw: "220,000–300,000",usd: "$170–230", tier: "luxury",   tierKo: "럭셔리",
    buy: ["신세계 강남 주류관", "갤러리아 명품관", "현대백화점 주류"],
    online: ["https://masterofmalt.com"] },
  ENFP: { krw: "70,000–90,000",  usd: "$55–70",   tier: "mid",      tierKo: "미드레인지",
    buy: ["이마트 와인앤모어", "보틀벙커", "홈플러스"],
    online: ["https://thewhiskyexchange.com"] },
  ISTJ: { krw: "55,000–75,000",  usd: "$42–58",   tier: "value",    tierKo: "밸류",
    buy: ["이마트", "홈플러스", "GS25 주류특화점"],
    online: ["https://whiskybase.com"] },
  ISFJ: { krw: "75,000–100,000", usd: "$58–78",   tier: "mid",      tierKo: "미드레인지",
    buy: ["이마트 와인앤모어", "홈플러스 주류", "보틀벙커"],
    online: ["https://thewhiskyexchange.com"] },
  ESTJ: { krw: "120,000–160,000",usd: "$92–123",  tier: "premium",  tierKo: "프리미엄",
    buy: ["이마트 와인앤모어", "신세계 주류관", "현대백화점"],
    online: ["https://masterofmalt.com"] },
  ESFJ: { krw: "65,000–85,000",  usd: "$50–66",   tier: "mid",      tierKo: "미드레인지",
    buy: ["홈플러스 주류", "이마트 와인앤모어", "GS25"],
    online: ["https://whiskybase.com"] },
  ISTP: { krw: "55,000–75,000",  usd: "$43–58",   tier: "value",    tierKo: "밸류",
    buy: ["이마트 와인앤모어", "홈플러스", "보틀벙커"],
    online: ["https://thewhiskyexchange.com"] },
  ISFP: { krw: "75,000–100,000", usd: "$58–78",   tier: "mid",      tierKo: "미드레인지",
    buy: ["이마트 와인앤모어", "홈플러스 주류", "보틀벙커"],
    online: ["https://thewhiskyexchange.com"] },
  ESTP: { krw: "60,000–80,000",  usd: "$46–62",   tier: "value",    tierKo: "밸류",
    buy: ["이마트 와인앤모어", "홈플러스", "GS25 주류특화점"],
    online: ["https://thewhiskyexchange.com"] },
  ESFP: { krw: "38,000–52,000",  usd: "$30–40",   tier: "entry",    tierKo: "엔트리",
    buy: ["이마트", "홈플러스", "GS25", "CU"],
    online: ["https://drizly.com"] },
},

// Today's mood → whisky mapping
MOOD_DATA: [
  { id:'energetic',  emoji:'🔥', ko:'활기찬',   en:'Energetic',  types:['ESTP','ENTJ','ENTP'],       desc:{ko:'강렬하고 힘찬 오늘, 도전적인 위스키가 어울려요', en:'Bold energy calls for a bold dram'} },
  { id:'calm',       emoji:'🌙', ko:'차분한',   en:'Calm',       types:['INTJ','INFJ','ISFJ'],       desc:{ko:'조용하고 내향적인 밤, 깊고 복잡한 위스키와 함께', en:'Quiet nights deserve deep, contemplative drams'} },
  { id:'complex',    emoji:'💭', ko:'복잡한',   en:'Pensive',    types:['INTP','INTJ','INFJ'],       desc:{ko:'생각이 많은 날엔 복층적인 풍미의 위스키를', en:'A busy mind needs a whisky with layers to unpack'} },
  { id:'sweet',      emoji:'🍯', ko:'달콤한',   en:'Sweet',      types:['ENFP','ESFP','INFP'],       desc:{ko:'달달한 기분, 부드럽고 달콤한 위스키 한 잔', en:'Sweet vibes, sweet drams — fruit and caramel await'} },
  { id:'intense',    emoji:'⚡', ko:'강렬한',   en:'Intense',    types:['ENTJ','ISTP','ESTP'],       desc:{ko:'강한 자극이 필요한 날, 피트와 스모크로 각성을', en:'You need something that bites back today'} },
  { id:'relaxed',    emoji:'😌', ko:'여유로운', en:'Relaxed',    types:['ISFJ','ESFJ','INFP'],       desc:{ko:'느긋한 하루, 부드럽고 꿀향의 위스키와 함께', en:'Slow down with something soft and honeyed'} },
  { id:'excited',    emoji:'🎉', ko:'신나는',   en:'Excited',    types:['ENFP','ESFP','ENFJ'],       desc:{ko:'신나는 오늘엔 밝고 생동감 넘치는 위스키로!', en:'Celebrate with something tropical and vibrant'} },
  { id:'focused',    emoji:'🎯', ko:'집중하는', en:'Focused',    types:['INTJ','ISTJ','ENTJ'],       desc:{ko:'집중력이 필요한 날, 클래식하고 묵직한 위스키', en:'Sharp mind, sharp dram — structured and reliable'} },
  { id:'romantic',   emoji:'🌹', ko:'낭만적인', en:'Romantic',   types:['INFJ','ISFP','ENFJ'],       desc:{ko:'감성적인 밤엔 우아하고 과일향의 위스키를', en:'Velvety, fruity and elegant for a romantic evening'} },
  { id:'adventurous',emoji:'🌊', ko:'모험적인', en:'Adventurous',types:['ENTP','ESTP','ISFP'],       desc:{ko:'새로운 것을 탐험하고 싶은 날, 독특한 위스키로', en:'Break the routine with something unexpected'} },
  { id:'nostalgic',  emoji:'🕰️', ko:'그리운',  en:'Nostalgic',  types:['ISTJ','INFP','ISFJ'],       desc:{ko:'추억에 잠기는 날엔 클래식하고 따뜻한 위스키', en:'Timeless classics for a walk down memory lane'} },
  { id:'social',     emoji:'🥂', ko:'사교적인', en:'Social',     types:['ESFJ','ENFJ','ESFP'],       desc:{ko:'함께하는 자리엔 누구나 즐길 수 있는 위스키', en:'Easy-drinking crowd-pleasers for good company'} },
],

// Biorhythm whisky modifiers: which MBTI sub-types fit each state
BIORHYTHM_MAP: {
  // physical high → bold, intense
  physical_high:   ["ESTP","ENTJ","ENTP","ISTP"],
  // physical low  → gentle, smooth
  physical_low:    ["ISFJ","INFP","ESFP","ISFP"],
  // emotional high → warm, sweet
  emotional_high:  ["ENFJ","INFJ","ENFP","ESFJ"],
  // emotional low  → dry, complex
  emotional_low:   ["INTJ","INTP","ISTJ","ENTJ"],
  // intellectual high → complex, layered
  intellectual_high:["INTJ","INTP","INFJ","ENTJ"],
  // intellectual low  → easy, fun
  intellectual_low: ["ESFP","ENFP","ESFJ","ESTP"],
},

MBTI_GRID: [
  ["INTJ","INTP","ENTJ","ENTP"],
  ["INFJ","INFP","ENFJ","ENFP"],
  ["ISTJ","ISFJ","ESTJ","ESFJ"],
  ["ISTP","ISFP","ESTP","ESFP"],
],

};
